### PR TITLE
Fix a couple small grammar issues and add section separators

### PR DESCRIPTION
**Pull request by Protowalker**

### CODE REVIEW

**Comment by nonunknown** [comment]
sorry I dont see any grammar issues, where you corrected them! If you have ideas on improving this repo visually, you're very welcome!

**Comment by Protowalker** [comment]
@nonunknown 

In English, questions and declarations have slightly different structures. Instead of asking `what this is?` you would ask `what is this?`

Another issue was `a most powerful engine that already is`. The first issue is that `most` is a unique descriptor -- what I mean is that only one thing can be the "most" something. Because of that, saying `a most` isn't correct. Instead, you would either want `the most` or `a more`. "The most" means the single engine that is more powerful than all the others, while "a more" would mean it would be more powerful than it was before adding these tools.

`that already is` also isn't quite correct.  I believe what you're trying to say is "make it more powerful than it is now", in which case you want `than it already is` -- alternatively, if you mean "make it the most powerful engine", then you would want `the most powerful engine there is.`

I hope these help! I also reverted those visual changes (with the equal signs) back to how you had them originally, as I ended up liking yours better.

**Comment by nonunknown** [comment]
ok then, so make the changes and do another PR

**Comment by Protowalker** [comment]
Those are the changes I made in this pull request

**Pull request merged**
